
name: e-commerce
services:
  auth:
    build:
      context: ./../auth
      dockerfile: ./../auth/auth.dockerfile
    image: auth:latest
    ports:
      - "8082:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATABASE_URL=host=postgres port=5432 user=postgres password=root dbname=authentication sslmode=disable timezone=UTC
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:17.5-alpine3.22"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./db-data/postgres/:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=authentication
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5